from dataclasses import dataclass, field
from typing import Literal


ResourceType = Literal["course", "project", "tutorial", "article", "video", "assessment"]
ResourceDifficulty = Literal["beginner", "intermediate", "advanced"]


@dataclass(frozen=True)
class LearningResource:
    id: str
    title: str
    type: ResourceType
    provider: str
    url: str
    description: str
    skills: tuple[str, ...]
    difficulty: ResourceDifficulty
    estimated_hours: int
    learning_formats: tuple[str, ...] = field(default_factory=tuple)
    prerequisites: tuple[str, ...] = field(default_factory=tuple)
    project_based: bool = False


LEARNING_RESOURCES: tuple[LearningResource, ...] = (
    LearningResource(
        "genai-python-001",
        "Python for Everybody",
        "course",
        "University of Michigan",
        "https://www.py4e.com/",
        "A practical introduction to Python programming fundamentals.",
        ("Python",),
        "beginner",
        20,
        ("course", "reading", "video"),
    ),
    LearningResource(
        "genai-ml-001",
        "Machine Learning Specialization",
        "course",
        "DeepLearning.AI",
        "https://www.coursera.org/specializations/machine-learning-introduction",
        "A structured path through supervised learning, model evaluation, and core ML concepts.",
        ("Machine Learning",),
        "intermediate",
        36,
        ("course", "video", "assessment"),
        ("Python",),
    ),
    LearningResource(
        "genai-dl-001",
        "Neural Networks and Deep Learning",
        "course",
        "DeepLearning.AI",
        "https://www.coursera.org/learn/neural-networks-deep-learning",
        "A focused course on neural network foundations and training workflows.",
        ("Deep Learning",),
        "intermediate",
        18,
        ("course", "video", "assessment"),
        ("Machine Learning",),
    ),
    LearningResource(
        "genai-transformers-001",
        "The Illustrated Transformer",
        "article",
        "Jay Alammar",
        "https://jalammar.github.io/illustrated-transformer/",
        "A visual explanation of transformer architecture and attention.",
        ("Transformers", "Deep Learning"),
        "intermediate",
        3,
        ("reading", "visual"),
        ("Machine Learning", "Deep Learning"),
    ),
    LearningResource(
        "genai-llm-001",
        "Generative AI for Everyone",
        "course",
        "DeepLearning.AI",
        "https://www.coursera.org/learn/generative-ai-for-everyone",
        "A beginner-friendly overview of generative AI concepts, capabilities, and limits.",
        ("LLM Fundamentals", "Prompt Engineering"),
        "beginner",
        6,
        ("course", "video"),
    ),
    LearningResource(
        "genai-prompt-001",
        "ChatGPT Prompt Engineering for Developers",
        "course",
        "DeepLearning.AI",
        "https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/",
        "A concise course on reliable prompting patterns for LLM applications.",
        ("Prompt Engineering", "LLM Fundamentals"),
        "beginner",
        2,
        ("course", "video", "hands_on"),
        ("LLM Fundamentals",),
    ),
    LearningResource(
        "genai-rag-project-001",
        "Build a Retrieval-Augmented Generation Assistant",
        "project",
        "FusionPath",
        "https://fusionpath.local/resources/build-rag-assistant",
        "Build a document question-answering assistant using embeddings, retrieval, and an LLM.",
        ("RAG", "Vector Databases", "LLM Fundamentals"),
        "intermediate",
        8,
        ("project", "hands_on"),
        ("LLM Fundamentals",),
        True,
    ),
    LearningResource(
        "genai-rag-tutorial-001",
        "Retrieval-Augmented Generation for Production Search",
        "tutorial",
        "FusionPath",
        "https://fusionpath.local/resources/rag-production-search",
        "Implement a RAG search flow with chunking, embeddings, retrieval, and answer grounding.",
        ("RAG", "Vector Databases"),
        "intermediate",
        8,
        ("tutorial", "reading", "hands_on"),
        ("LLM Fundamentals",),
    ),
    LearningResource(
        "genai-vector-001",
        "Vector Databases and Embeddings Primer",
        "article",
        "FusionPath",
        "https://fusionpath.local/resources/vector-databases-primer",
        "Learn embeddings, similarity search, metadata filters, and common vector database patterns.",
        ("Vector Databases",),
        "beginner",
        3,
        ("reading",),
        ("Machine Learning",),
    ),
    LearningResource(
        "genai-eval-001",
        "Evaluating LLM Applications",
        "tutorial",
        "OpenAI Cookbook",
        "https://cookbook.openai.com/examples/evaluation/getting_started_with_openai_evals",
        "A practical guide to evaluation concepts for language model applications.",
        ("LLM Evaluation", "LLM Fundamentals"),
        "advanced",
        6,
        ("tutorial", "reading", "hands_on"),
        ("LLM Fundamentals",),
    ),
    LearningResource(
        "genai-api-001",
        "FastAPI Tutorial",
        "tutorial",
        "FastAPI",
        "https://fastapi.tiangolo.com/tutorial/",
        "Build HTTP APIs with Python, validation, routing, and OpenAPI documentation.",
        ("APIs", "Python"),
        "intermediate",
        10,
        ("tutorial", "reading", "hands_on"),
        ("Python",),
    ),
    LearningResource(
        "data-sql-001",
        "SQLBolt Interactive SQL Lessons",
        "tutorial",
        "SQLBolt",
        "https://sqlbolt.com/",
        "Interactive SQL lessons covering selects, joins, filtering, and aggregation.",
        ("SQL",),
        "beginner",
        6,
        ("tutorial", "hands_on"),
    ),
    LearningResource(
        "data-sql-002",
        "Mode SQL Tutorial",
        "tutorial",
        "Mode",
        "https://mode.com/sql-tutorial/",
        "A practical SQL tutorial using analytics-style examples.",
        ("SQL", "Business Metrics"),
        "intermediate",
        8,
        ("tutorial", "reading", "hands_on"),
    ),
    LearningResource(
        "data-spreadsheet-001",
        "Google Sheets Training",
        "course",
        "Google",
        "https://support.google.com/a/users/answer/9282959",
        "Official training for spreadsheet formulas, analysis, and collaboration workflows.",
        ("Spreadsheets",),
        "beginner",
        5,
        ("course", "reading"),
    ),
    LearningResource(
        "data-python-001",
        "Python Data Science Handbook",
        "article",
        "Jake VanderPlas",
        "https://jakevdp.github.io/PythonDataScienceHandbook/",
        "A reference-style path through NumPy, pandas, visualization, and ML basics.",
        ("Python", "Data Cleaning", "Data Visualization"),
        "intermediate",
        18,
        ("reading", "hands_on"),
        ("Python",),
    ),
    LearningResource(
        "data-statistics-001",
        "OpenIntro Statistics",
        "course",
        "OpenIntro",
        "https://www.openintro.org/book/os/",
        "A free statistics textbook for probability, inference, and regression foundations.",
        ("Statistics",),
        "beginner",
        24,
        ("course", "reading", "assessment"),
    ),
    LearningResource(
        "data-cleaning-project-001",
        "Clean and Analyze a Messy Sales Dataset",
        "project",
        "FusionPath",
        "https://fusionpath.local/resources/messy-sales-analysis",
        "Clean raw sales data, define metrics, and prepare an analysis-ready dataset.",
        ("Data Cleaning", "SQL", "Business Metrics"),
        "intermediate",
        7,
        ("project", "hands_on"),
        ("SQL",),
        True,
    ),
    LearningResource(
        "data-viz-001",
        "Data Visualization Curriculum",
        "course",
        "Kaggle Learn",
        "https://www.kaggle.com/learn/data-visualization",
        "Hands-on lessons for building clear charts with Python visualization tools.",
        ("Data Visualization", "Python"),
        "intermediate",
        4,
        ("course", "hands_on"),
        ("Python",),
    ),
    LearningResource(
        "data-bi-001",
        "Microsoft Power BI Guided Learning",
        "course",
        "Microsoft",
        "https://learn.microsoft.com/en-us/training/powerplatform/power-bi",
        "Official modules for building Power BI reports and dashboards.",
        ("BI Tools", "Data Visualization"),
        "intermediate",
        12,
        ("course", "video", "hands_on"),
    ),
    LearningResource(
        "data-story-001",
        "Storytelling With Data",
        "article",
        "Storytelling With Data",
        "https://www.storytellingwithdata.com/blog",
        "Articles on communicating insights with concise, audience-aware data stories.",
        ("Communication", "Data Visualization"),
        "intermediate",
        4,
        ("reading",),
        ("Data Visualization",),
    ),
    LearningResource(
        "frontend-html-css-001",
        "Responsive Web Design",
        "course",
        "freeCodeCamp",
        "https://www.freecodecamp.org/learn/2022/responsive-web-design/",
        "Project-based HTML and CSS fundamentals for responsive layouts.",
        ("HTML", "CSS", "Accessibility"),
        "beginner",
        25,
        ("course", "project", "hands_on"),
        (),
        True,
    ),
    LearningResource(
        "frontend-js-001",
        "JavaScript Algorithms and Data Structures",
        "course",
        "freeCodeCamp",
        "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/",
        "Hands-on JavaScript lessons covering core syntax, functions, and data structures.",
        ("JavaScript",),
        "beginner",
        30,
        ("course", "project", "hands_on"),
        (),
        True,
    ),
    LearningResource(
        "frontend-ts-001",
        "TypeScript Handbook",
        "article",
        "Microsoft",
        "https://www.typescriptlang.org/docs/handbook/intro.html",
        "Official TypeScript documentation for types, narrowing, generics, and tooling.",
        ("TypeScript",),
        "intermediate",
        8,
        ("reading",),
        ("JavaScript",),
    ),
    LearningResource(
        "frontend-react-001",
        "React Learn",
        "course",
        "React",
        "https://react.dev/learn",
        "Official React lessons covering components, state, effects, and rendering.",
        ("React", "State Management"),
        "intermediate",
        12,
        ("course", "reading", "hands_on"),
        ("JavaScript",),
    ),
    LearningResource(
        "frontend-react-project-001",
        "Build an Accessible React Dashboard",
        "project",
        "FusionPath",
        "https://fusionpath.local/resources/accessible-react-dashboard",
        "Build a React dashboard with reusable components, API integration, and accessible UI states.",
        ("React", "APIs", "Accessibility", "State Management"),
        "intermediate",
        10,
        ("project", "hands_on"),
        ("React", "JavaScript"),
        True,
    ),
    LearningResource(
        "frontend-api-001",
        "Working With APIs in JavaScript",
        "tutorial",
        "MDN",
        "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Client-side_APIs",
        "Learn browser API integration patterns and client-side HTTP requests.",
        ("APIs", "JavaScript"),
        "intermediate",
        6,
        ("tutorial", "reading", "hands_on"),
        ("JavaScript",),
    ),
    LearningResource(
        "frontend-testing-001",
        "Testing Library React Examples",
        "tutorial",
        "Testing Library",
        "https://testing-library.com/docs/react-testing-library/example-intro/",
        "Practical examples for testing React components from a user perspective.",
        ("Testing", "React"),
        "intermediate",
        5,
        ("tutorial", "reading", "hands_on"),
        ("React",),
    ),
    LearningResource(
        "frontend-a11y-001",
        "Learn Accessibility",
        "course",
        "web.dev",
        "https://web.dev/learn/accessibility",
        "A structured accessibility course for semantic HTML, focus, and inclusive interfaces.",
        ("Accessibility", "HTML", "CSS"),
        "beginner",
        8,
        ("course", "reading"),
    ),
    LearningResource(
        "backend-python-001",
        "Python for Everybody",
        "course",
        "University of Michigan",
        "https://www.py4e.com/",
        "A practical introduction to Python programming fundamentals.",
        ("Python",),
        "beginner",
        20,
        ("course", "reading", "video"),
    ),
    LearningResource(
        "backend-api-001",
        "FastAPI Tutorial",
        "tutorial",
        "FastAPI",
        "https://fastapi.tiangolo.com/tutorial/",
        "Build HTTP APIs with Python, validation, routing, and OpenAPI documentation.",
        ("APIs", "Python"),
        "intermediate",
        10,
        ("tutorial", "reading", "hands_on"),
        ("Python",),
    ),
    LearningResource(
        "backend-api-project-001",
        "Build a Tested REST API",
        "project",
        "FusionPath",
        "https://fusionpath.local/resources/tested-rest-api",
        "Build a REST API with validation, error handling, tests, and OpenAPI documentation.",
        ("APIs", "Testing", "System Design"),
        "intermediate",
        12,
        ("project", "hands_on"),
        ("Python",),
        True,
    ),
    LearningResource(
        "backend-db-001",
        "Database Design Basics",
        "course",
        "Microsoft Learn",
        "https://learn.microsoft.com/en-us/training/modules/design-a-data-model/",
        "Learn data modeling concepts, relationships, normalization, and schema tradeoffs.",
        ("Databases", "SQL"),
        "beginner",
        5,
        ("course", "reading"),
    ),
    LearningResource(
        "backend-sql-001",
        "SQLBolt Interactive SQL Lessons",
        "tutorial",
        "SQLBolt",
        "https://sqlbolt.com/",
        "Interactive SQL lessons covering selects, joins, filtering, and aggregation.",
        ("SQL",),
        "beginner",
        6,
        ("tutorial", "hands_on"),
    ),
    LearningResource(
        "backend-auth-001",
        "OAuth 2.0 and OpenID Connect Overview",
        "article",
        "Auth0",
        "https://auth0.com/docs/get-started/authentication-and-authorization-flow",
        "An overview of authentication and authorization flows for backend systems.",
        ("Authentication", "APIs"),
        "intermediate",
        4,
        ("reading",),
        ("APIs",),
    ),
    LearningResource(
        "backend-testing-001",
        "Effective Python Testing With pytest",
        "tutorial",
        "Real Python",
        "https://realpython.com/pytest-python-testing/",
        "A practical introduction to writing Python tests with pytest.",
        ("Testing", "Python"),
        "intermediate",
        6,
        ("tutorial", "reading", "hands_on"),
        ("Python",),
    ),
    LearningResource(
        "backend-system-001",
        "System Design Primer",
        "article",
        "GitHub",
        "https://github.com/donnemartin/system-design-primer",
        "A broad reference for backend architecture, scalability, APIs, caching, and storage.",
        ("System Design", "APIs", "Databases"),
        "advanced",
        20,
        ("reading",),
        ("APIs", "Databases"),
    ),
    LearningResource(
        "devops-linux-001",
        "Linux Journey",
        "course",
        "Linux Journey",
        "https://linuxjourney.com/",
        "Beginner-friendly Linux command line, processes, permissions, and networking lessons.",
        ("Linux", "Scripting"),
        "beginner",
        12,
        ("course", "reading", "hands_on"),
    ),
    LearningResource(
        "devops-networking-001",
        "Computer Networking: A Top-Down Approach Resources",
        "course",
        "Kurose/Ross",
        "https://gaia.cs.umass.edu/kurose_ross/online_lectures.htm",
        "Video lectures on core networking layers, protocols, and architecture.",
        ("Networking",),
        "intermediate",
        15,
        ("course", "video"),
    ),
    LearningResource(
        "devops-cloud-001",
        "AWS Cloud Practitioner Essentials",
        "course",
        "AWS Skill Builder",
        "https://explore.skillbuilder.aws/learn/course/external/view/elearning/134/aws-cloud-practitioner-essentials",
        "Foundational cloud concepts, AWS services, billing, security, and architecture basics.",
        ("Cloud Platforms",),
        "beginner",
        6,
        ("course", "video"),
    ),
    LearningResource(
        "devops-docker-001",
        "Docker Get Started",
        "tutorial",
        "Docker",
        "https://docs.docker.com/get-started/",
        "Official Docker tutorial covering images, containers, Dockerfiles, and app packaging.",
        ("Docker",),
        "beginner",
        5,
        ("tutorial", "reading", "hands_on"),
        ("Linux",),
    ),
    LearningResource(
        "devops-k8s-001",
        "Kubernetes Basics",
        "tutorial",
        "Kubernetes",
        "https://kubernetes.io/docs/tutorials/kubernetes-basics/",
        "Official tutorial for deployments, pods, services, scaling, and updates.",
        ("Kubernetes",),
        "intermediate",
        8,
        ("tutorial", "reading", "hands_on"),
        ("Docker",),
    ),
    LearningResource(
        "devops-cicd-001",
        "GitHub Actions Documentation",
        "tutorial",
        "GitHub",
        "https://docs.github.com/en/actions",
        "Learn workflow automation, CI/CD jobs, events, actions, and deployment pipelines.",
        ("CI/CD", "Git"),
        "intermediate",
        8,
        ("tutorial", "reading", "hands_on"),
        ("Git",),
    ),
    LearningResource(
        "devops-iac-001",
        "Terraform Tutorials",
        "tutorial",
        "HashiCorp",
        "https://developer.hashicorp.com/terraform/tutorials",
        "Hands-on Terraform tutorials for provisioning cloud infrastructure as code.",
        ("Infrastructure as Code", "Cloud Platforms"),
        "intermediate",
        10,
        ("tutorial", "reading", "hands_on"),
        ("Cloud Platforms",),
    ),
    LearningResource(
        "devops-monitoring-001",
        "Prometheus Getting Started",
        "tutorial",
        "Prometheus",
        "https://prometheus.io/docs/prometheus/latest/getting_started/",
        "Learn monitoring basics with metrics collection, queries, and alerting concepts.",
        ("Monitoring",),
        "intermediate",
        5,
        ("tutorial", "reading", "hands_on"),
    ),
    LearningResource(
        "shared-git-001",
        "Git Handbook",
        "article",
        "GitHub",
        "https://guides.github.com/introduction/git-handbook/",
        "A concise guide to Git concepts, commits, branches, and collaboration workflows.",
        ("Git",),
        "beginner",
        3,
        ("reading",),
    ),
    LearningResource(
        "shared-git-project-001",
        "Practice Git Branching",
        "tutorial",
        "Learn Git Branching",
        "https://learngitbranching.js.org/",
        "Interactive Git exercises for commits, branches, merging, rebasing, and remotes.",
        ("Git",),
        "intermediate",
        4,
        ("tutorial", "hands_on"),
    ),
)
