"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, BookOpen, Bot, CheckCircle2, Compass, Lightbulb, Play, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { defaultLearnerState, hydrateLearnerState, saveLearnerState, type LearnerState } from "@/lib/learner-store";
import { cn } from "@/lib/utils";

export type WorkspaceView = "dashboard" | "roadmap" | "learn" | "practice" | "projects" | "graph" | "career" | "tutor" | "progress" | "profile";
const mission = { title: "Learn AWS IAM fundamentals", duration: "25 minutes", reason: "IAM is required for the AWS deployment milestone you’re working toward." };
const milestones = [
  { title: "Foundations", skills: ["Linux", "Networking"], status: "complete", why: "Build the operating and network fundamentals every cloud deployment depends on." },
  { title: "Backend", skills: ["Java", "Spring Boot"], status: "complete", why: "Turn your existing backend strengths into deployable services." },
  { title: "Cloud", skills: ["AWS", "Docker", "CI/CD"], status: "current", why: "Learn to package and securely deploy your services on AWS." },
  { title: "Infrastructure", skills: ["Kubernetes", "Terraform"], status: "locked", why: "Automate and operate cloud workloads at scale." },
  { title: "Production", skills: ["Monitoring", "Security"], status: "locked", why: "Make systems observable, dependable, and safe." },
];

export function LearningWorkspace({ view }: { view: WorkspaceView }) {
  const [state, setState] = useState<LearnerState>(defaultLearnerState);
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => { void hydrateLearnerState().then((next) => { setState(next); setHydrated(true); }); }, []);
  function update(next: LearnerState) { setState(next); void saveLearnerState(next); }
  if (!hydrated) return <main className="container py-10"><div className="h-72 animate-pulse rounded-xl bg-secondary" /></main>;
  const views: Record<WorkspaceView, React.ReactNode> = {
    dashboard: <Dashboard state={state} update={update} />,
    roadmap: <Roadmap state={state} />,
    learn: <Learn state={state} update={update} />,
    practice: <Practice state={state} update={update} />,
    projects: <Projects state={state} update={update} />,
    graph: <Graph state={state} />,
    career: <Career state={state} />,
    tutor: <Tutor state={state} />,
    progress: <Analytics state={state} />,
    profile: <Profile state={state} />,
  };
  return <main className="min-h-[calc(100vh-5rem)] bg-slate-50 text-slate-900">{views[view]}</main>;
}

function Page({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="mx-auto max-w-7xl px-4 py-8 sm:px-7 lg:py-10"><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-700">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl">{title}</h1>{children}</section>; }
function Dashboard({ state, update }: { state: LearnerState; update: (s: LearnerState) => void }) {
  const start = () => update({ ...state, completedLessons: [...new Set([...state.completedLessons, mission.title])], activity: { ...state.activity, minutes: state.activity.minutes + 25 }, readiness: Math.min(100, state.readiness + 2) });
  return <Page eyebrow="Personal learning command center" title={`Good morning, ${state.name}`}><p className="mt-2 text-slate-600">Your goal: <b>{state.goal}</b> · You’re {state.readiness}% career-ready.</p><div className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl bg-[#081b3d] p-6 text-white shadow-xl sm:p-8"><p className="text-xs font-bold tracking-[.16em] text-blue-200">CAREER READINESS</p><div className="mt-4 flex items-end justify-between"><p className="text-6xl font-semibold">{state.readiness}%</p><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-sm text-emerald-300">↑ 8% this month</span></div><p className="mt-6 text-blue-100">Target: {state.goal} · Estimated readiness: 5 months</p><Progress className="mt-4 bg-white/15" value={state.readiness} /></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold tracking-[.16em] text-slate-500">THIS WEEK</p><div className="mt-5 grid grid-cols-2 gap-4 text-center"><Metric value={`${state.activity.minutes}m`} label="Learning"/><Metric value={state.activity.questions} label="Practice"/><Metric value={state.activity.projects} label="Projects"/><Metric value={state.skills.filter(s=>s.mastery>=75).length} label="Strong skills"/></div></section></div><section className="mt-5 rounded-2xl border border-blue-200 bg-gradient-to-r from-blue-50 to-white p-6 shadow-sm"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold tracking-[.16em] text-blue-700">TODAY’S MISSION</p><h2 className="mt-2 text-2xl font-semibold">{mission.title}</h2><p className="mt-2 max-w-2xl text-sm text-slate-600">{mission.duration} · Why this matters: {mission.reason}</p></div><Button onClick={start} className="bg-blue-700 hover:bg-blue-800">{state.completedLessons.includes(mission.title) ? "Completed" : "Start learning"}<ArrowRight /></Button></div></section><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_.8fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">Skill health</h2><div className="mt-5 space-y-4">{state.skills.slice(0,6).map(s=><SkillBar key={s.name} {...s}/>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-xs font-bold tracking-[.16em] text-blue-700">ONE CLEAR NEXT STEP</p><h2 className="mt-3 text-xl font-semibold">Complete Docker networking before starting Kubernetes.</h2><p className="mt-3 text-sm leading-6 text-slate-600">It unlocks a foundational concept for container orchestration and keeps your roadmap efficient.</p><Button asChild variant="outline" className="mt-5"><Link href="/roadmap">View roadmap <Compass /></Link></Button></section></div></Page>;
}
function Metric({ value, label }: { value: string|number; label: string }) { return <div><p className="text-2xl font-semibold text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>; }
function SkillBar({ name, mastery, status }: { name:string; mastery:number; status:string }) { return <div><div className="mb-2 flex justify-between text-sm"><span className="font-medium">{name}</span><span className="text-slate-500">{mastery}% · {status}</span></div><Progress value={mastery}/></div>; }
function Roadmap({ state }: { state: LearnerState }) { const [open, setOpen] = useState(2); return <Page eyebrow="Adaptive learning plan" title="Career roadmap"><p className="mt-2 text-slate-600">A sequenced path that responds to your assessment evidence.</p>{state.adapted && <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><b>Roadmap adjusted.</b> Your AWS networking assessment identified a gap, so VPC Essentials is now scheduled before Docker.</div>}<div className="mt-8 space-y-3">{milestones.map((m,i)=><article key={m.title} className={cn("rounded-xl border bg-white p-5 shadow-sm",m.status==="current"&&"border-blue-300 ring-1 ring-blue-100")}><button className="flex w-full items-center justify-between text-left" onClick={()=>setOpen(open===i?-1:i)}><div className="flex items-center gap-4"><span className={cn("flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold",m.status==="complete"?"bg-emerald-100 text-emerald-700":m.status==="current"?"bg-blue-700 text-white":"bg-slate-100 text-slate-500")}>{m.status==="complete"?"✓":String(i+1).padStart(2,"0")}</span><div><h2 className="font-semibold">{m.title} {m.status==="current"&&<span className="ml-2 text-xs font-medium text-blue-700">CURRENT</span>}</h2><p className="text-sm text-slate-500">{m.skills.join(" · ")}</p></div></div><span className="text-sm text-slate-500">{open===i?"Hide":"View"}</span></button>{open===i&&<div className="mt-5 border-t pt-4 text-sm text-slate-600"><p>{m.why}</p>{m.title==="Cloud"&&state.adapted&&<p className="mt-3 rounded-lg bg-blue-50 p-3 text-blue-950"><b>Inserted prerequisite:</b> VPC fundamentals → Subnets → Routing → Security Groups → AWS assessment</p>}<div className="mt-4 flex gap-3"><Button size="sm">Continue milestone <ArrowRight /></Button><Button size="sm" variant="outline">Take assessment</Button></div></div>}</article>)}</div></Page>; }
function Learn({ state, update }: { state:LearnerState;update:(s:LearnerState)=>void }) { return <Page eyebrow="Focused learning" title="Learn AWS IAM fundamentals"><div className="mt-8 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><article className="rounded-2xl bg-[#081b3d] p-8 text-white"><BookOpen className="h-8 w-8 text-blue-200"/><h2 className="mt-7 text-2xl font-semibold">Identity is the control plane for your cloud.</h2><p className="mt-4 max-w-xl leading-7 text-blue-100">IAM defines who can access AWS resources and what actions they can perform. Start with users, roles, policies, and least privilege.</p><Button className="mt-7 bg-white text-slate-900 hover:bg-slate-100" onClick={()=>update({...state,activity:{...state.activity,minutes:state.activity.minutes+15}})}><Play/> Mark 15 min studied</Button></article><aside className="rounded-2xl border bg-white p-6"><h2 className="font-semibold">Up next</h2><ol className="mt-4 space-y-4 text-sm text-slate-600"><li>1. IAM users and roles</li><li>2. Policy evaluation logic</li><li>3. Least-privilege lab</li></ol><Link href="/tutor" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-blue-700">Need an explanation? Ask Tutor <Bot className="h-4 w-4"/></Link></aside></div></Page>; }
function Practice({ state, update }: {state:LearnerState;update:(s:LearnerState)=>void}) { const [answer,setAnswer]=useState<string|null>(null); const correct=answer==="B"; const submit=(a:string)=>{setAnswer(a);const next={...state,activity:{...state.activity,questions:state.activity.questions+1}};if(a!=="B")next.mistakes={...state.mistakes,"Security groups vs NACLs":(state.mistakes["Security groups vs NACLs"]??0)+1};else next.skills=state.skills.map(s=>s.name==="AWS"?{...s,mastery:Math.min(100,s.mastery+4)}:s);if(a!=="B"&&(next.mistakes["Security groups vs NACLs"]>=3))next.adapted=true;update(next);}; return <Page eyebrow="Practice center" title="AWS networking"><div className="mt-6 flex flex-wrap gap-2">{["AWS","Intermediate","Scenario","Networking"].map(x=><span key={x} className="rounded-full bg-slate-200 px-3 py-1 text-xs font-medium">{x}</span>)}</div><article className="mt-6 max-w-3xl rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm font-medium text-blue-700">Scenario · Question 4 of 10</p><h2 className="mt-4 text-xl font-semibold">Which control is stateful and applies at the instance level in an AWS VPC?</h2><div className="mt-6 grid gap-3">{[["A","Network ACL"],["B","Security group"],["C","Route table"],["D","Internet gateway"]].map(([key,label])=><button key={key} onClick={()=>submit(key)} className={cn("rounded-xl border p-4 text-left text-sm hover:border-blue-500",answer===key&&(correct?"border-emerald-500 bg-emerald-50":"border-rose-400 bg-rose-50"))}>{key}. {label}</button>)}</div>{answer&&<div className={cn("mt-6 rounded-xl p-4 text-sm",correct?"bg-emerald-50 text-emerald-950":"bg-amber-50 text-amber-950")}><b>{correct?"Correct — solid distinction.":"Your approach is close."}</b> {correct?"Security groups are stateful and attach to ENIs/instances.":"A Network ACL is stateless and works at subnet level; a security group is stateful and works at the instance level."}<div className="mt-3"><Button size="sm" variant="outline" onClick={()=>setAnswer(null)}>{correct?"Next question":"Try again"}</Button></div></div>}</article><section className="mt-8 rounded-2xl border bg-white p-6"><h2 className="font-semibold">Mistake journal</h2><p className="mt-1 text-sm text-slate-500">Patterns become the next useful practice session.</p><div className="mt-4 space-y-3">{Object.entries(state.mistakes).map(([m,count])=><div key={m} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>AWS · {m}</span><b>{count} mistakes</b></div>)}</div></section></Page>; }
function Projects({ state, update }: {state:LearnerState;update:(s:LearnerState)=>void}) { const [started,setStarted]=useState(false); return <Page eyebrow="Project lab" title="Build proof of your skills"><article className="mt-7 rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-sm font-semibold text-blue-700">INTERMEDIATE · 5 HOURS</p><h2 className="mt-2 text-2xl font-semibold">Deploy a Spring Boot API on AWS</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Package a REST API, configure EC2, deploy it safely, and add basic monitoring.</p></div><Button onClick={()=>{setStarted(true);update({...state,activity:{...state.activity,projects:Math.max(1,state.activity.projects)}})}}>{started?"Project started":"Start project"}<ArrowRight/></Button></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Build API","Containerize","Configure EC2","Deploy & monitor"].map((t,i)=><div key={t} className="flex items-center gap-3 rounded-lg bg-slate-50 p-3 text-sm"><CheckCircle2 className={cn("h-4 w-4",started&&i===0?"text-emerald-600":"text-slate-300")}/>{t}</div>)}</div>{started&&<p className="mt-5 rounded-lg bg-blue-50 p-3 text-sm text-blue-950"><b>AI Project Mentor:</b> Share your Dockerfile, command, and error log if you get stuck. I’ll guide the debugging process.</p>}</article></Page>; }
function Graph({ state }: {state:LearnerState}) { return <Page eyebrow="Skill dependencies" title="Your skill graph"><p className="mt-2 text-slate-600">Status is based on completed learning and practice performance.</p><div className="mt-8 overflow-x-auto rounded-2xl border bg-white p-8"><div className="min-w-[640px] text-center"><Node label="Cloud Engineer" status="strong"/><div className="mx-auto h-8 w-px bg-slate-300"/><div className="flex justify-center gap-16"><div><Node label="AWS" status="weak"/><div className="mx-auto h-7 w-px bg-slate-300"/><div className="flex gap-5"><Node label="IAM" status="strong"/><Node label="VPC" status="weak"/></div></div><div><Node label="Docker" status="learning"/><div className="mx-auto h-7 w-px bg-slate-300"/><Node label="Containers" status="learning"/></div><Node label="Networking" status="learning"/></div></div></div><div className="mt-5 flex flex-wrap gap-4 text-xs text-slate-500">{["Mastered","Strong","Learning","Weak","Locked"].map(x=><span key={x}>● {x}</span>)}</div></Page>; }
function Node({label,status}:{label:string;status:string}) { return <button className={cn("rounded-lg border px-4 py-2 text-sm font-medium",status==="weak"?"border-amber-300 bg-amber-50":status==="strong"?"border-emerald-300 bg-emerald-50":"border-blue-200 bg-blue-50")}>{label}<span className="sr-only">, {status}</span></button>; }
function Career({state}:{state:LearnerState}) { return <Page eyebrow="Career center" title="Cloud Engineer readiness"><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_.8fr]"><section className="rounded-2xl border bg-white p-6"><h2 className="font-semibold">Role requirements</h2><div className="mt-5 space-y-4">{state.skills.slice(2).map(s=><SkillBar key={s.name}{...s}/>)}</div></section><aside className="rounded-2xl border bg-white p-6"><h2 className="font-semibold">Readiness reasoning</h2><p className="mt-3 text-sm leading-6 text-slate-600">Your score reflects technical skills, project work, practice evidence, and interview preparation—not a vanity score.</p><ul className="mt-5 space-y-3 text-sm"><li>Technical skills <b className="float-right">62%</b></li><li>Practical experience <b className="float-right">58%</b></li><li>Problem solving <b className="float-right">70%</b></li><li>Projects <b className="float-right">50%</b></li></ul><Button asChild className="mt-6"><Link href="/practice">Practice weak skills <ArrowRight/></Link></Button></aside></div></Page>; }
function Tutor({state}:{state:LearnerState}) { const [messages,setMessages]=useState([{role:"coach",text:"I’m your FusionPath learning coach. You’re focused on AWS networking. I’ll start with a question, hint, or example—not a shortcut."}]); const [input,setInput]=useState(""); const send=(text:string)=>{if(!text.trim())return;setMessages([...messages,{role:"you",text},{role:"coach",text:`Let’s reason it out. What is the scope of the resource you’re considering, and is its traffic stateful? That distinction will guide the answer.`}]);setInput("");}; return <Page eyebrow="Contextual AI tutor" title="Learn with your coach"><div className="mt-7 max-w-3xl rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><p className="font-semibold">Current focus: AWS Networking</p><p className="mt-1 text-sm text-slate-500">Uses your roadmap, weak skills, and recent mistakes.</p></div><div className="min-h-72 space-y-4 p-5">{messages.map((m,i)=><div key={i} className={cn("max-w-[85%] rounded-xl p-3 text-sm leading-6",m.role==="you"?"ml-auto bg-blue-700 text-white":"bg-slate-100 text-slate-800")}>{m.text}</div>)}</div><div className="flex flex-wrap gap-2 border-t px-5 pt-4">{["Explain simply","Give me an example","Give me a hint","Test me","I’m stuck"].map(x=><button key={x} onClick={()=>send(x)} className="rounded-full border px-3 py-1.5 text-xs font-medium hover:border-blue-500">{x}</button>)}</div><form className="flex gap-2 p-5" onSubmit={e=>{e.preventDefault();send(input)}}><input value={input} onChange={e=>setInput(e.target.value)} className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm" aria-label="Ask the AI tutor" placeholder="Ask about your current lesson…"/><Button type="submit">Send</Button></form></div></Page>; }
function Analytics({state}:{state:LearnerState}) { return <Page eyebrow="Evidence-based progress" title="Your learning insights"><div className="mt-8 grid gap-5 sm:grid-cols-3"><MetricCard label="Learning time" value={`${state.activity.minutes} min`}/><MetricCard label="Practice questions" value={state.activity.questions}/><MetricCard label="Career readiness" value={`${state.readiness}%`}/></div><section className="mt-6 rounded-2xl border bg-white p-6"><h2 className="font-semibold">What FusionPath has learned</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Insight icon={<TrendingUp/>} text="You learn best in focused 30–45 minute sessions."/><Insight icon={<Lightbulb/>} text="Scenario-based AWS questions need more deliberate practice."/></div></section></Page>; }
function MetricCard({label,value}:{label:string;value:string|number}) { return <section className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></section>; } function Insight({icon,text}:{icon:React.ReactNode;text:string}) { return <div className="flex gap-3 rounded-xl bg-blue-50 p-4 text-sm text-blue-950"><span className="text-blue-700">{icon}</span>{text}</div>; }
function Profile({state}:{state:LearnerState}) { return <Page eyebrow="Learner profile" title={`${state.name}’s preferences`}><section className="mt-8 max-w-2xl rounded-2xl border bg-white p-6"><p className="text-sm text-slate-500">Career goal</p><p className="mt-1 text-lg font-semibold">{state.goal}</p><p className="mt-6 text-sm text-slate-500">Learning preference</p><p className="mt-1 text-lg font-semibold">Project-based, structured sessions</p><Button asChild variant="outline" className="mt-7"><Link href="/onboarding">Edit learning profile</Link></Button></section></Page>; }
